//! TypeScript bindings for the browser page, and the test that keeps them fresh.
//!
//! The web UI must never hand-write a wire shape: every DTO in this crate
//! derives `ts_rs::TS` under the `ts` feature, and this module exports them —
//! plus the handful of wire *constants* a client matches on — into
//! `web/src/generated/`, which is committed. [`bindings_are_up_to_date`]
//! regenerates into a temp dir and fails on any difference, so a protocol change
//! that forgets to regenerate is a red test rather than a silently stale page.
//!
//! Regenerate with:
//!
//! ```text
//! CC_TS_REGENERATE=1 cargo test -p claude-commander-protocol --features ts ts_export
//! ```

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::TS;

use crate::{api, comment, config, connection, diff, github, hosting, pr, session, workspace, ws};

/// Set to regenerate the committed bindings instead of checking them.
const REGENERATE_ENV: &str = "CC_TS_REGENERATE";

/// Header ts-rs puts on its own files; reused for the hand-assembled ones so
/// every file in the directory says the same thing.
const GENERATED_HEADER: &str = "// This file was generated by `claude-commander-protocol`'s `ts` feature \
     (src/ts_export.rs). Do not edit this file manually.\n";

/// The committed output directory, relative to the workspace root.
fn committed_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/generated")
}

/// Write every binding into `dir`.
fn export_into(dir: &Path) {
    // `u64`/`i64` fields (timestamps-in-millis, sizes, counters) arrive through
    // `JSON.parse` as plain numbers, so that is their honest type; ts-rs's
    // `bigint` default describes a value the browser never actually receives.
    // The one u64 whose precision matters (`ReviewSnapshot::content_hash`)
    // overrides its own type to `unknown` instead.
    let cfg = ts_rs::Config::new()
        .with_out_dir(dir)
        .with_large_int("number");

    macro_rules! export {
        ($($t:ty),* $(,)?) => {
            $( <$t as TS>::export_all(&cfg).unwrap_or_else(|e| {
                panic!("exporting {}: {e}", stringify!($t))
            }); )*
        };
    }
    export!(
        api::SessionInfo,
        api::SessionDetail,
        api::NewComment,
        api::ToggleReviewed,
        api::DiffSide,
        api::ReviewSnapshot,
        api::CreateSessionOpts,
        api::ProjectInfo,
        api::AddProjectRequest,
        api::PullBlockReason,
        api::PullStatus,
        api::OperationKind,
        api::OperationOutcome,
        api::OperationStatus,
        api::ServerStatus,
        api::Snapshot,
        api::AgentStatesSnapshot,
        api::PreviewData,
        api::DiffStat,
        api::ProgramInfo,
        api::SetProgramsRequest,
        api::CreateOptions,
        api::BranchInfo,
        api::RenameSession,
        api::SetSection,
        api::SetSessionBase,
        api::PrRetarget,
        api::SetSessionBaseOutcome,
        api::ChangeProgram,
        api::PatchSession,
        api::MarkUnread,
        // Generic: the declaration is `CreatedId<T>`; the argument here only
        // has to be something that implements `TS`.
        api::CreatedId<session::SessionId>,
        api::ReviewedToggle,
        api::ScanResponse,
        api::ConfigReloaded,
        api::PastedImage,
        api::ApiErrorBody,
        api::ApiErrorDetail,
        comment::CommentSide,
        comment::CommentStatus,
        comment::Comment,
        comment::ApplyOutcome,
        config::ConfigPatch,
        config::ConfigView,
        connection::ConnectionState,
        diff::LineOrigin,
        diff::DiffLine,
        diff::Hunk,
        diff::FileStatus,
        diff::BinaryKind,
        diff::BinaryInfo,
        diff::FileDiff,
        diff::ParsedDiff,
        github::GithubRepo,
        hosting::CloneSource,
        hosting::CodeHostProvider,
        hosting::CodeHost,
        hosting::HostedRepository,
        hosting::RepositoryListing,
        hosting::RepositoryVisibility,
        api::CodeHostStatus,
        github::CloneRequest,
        github::CloneJobId,
        github::CloneStatus,
        github::CloneJob,
        github::CloneTarget,
        pr::PrState,
        pr::ReviewDecision,
        session::ProjectId,
        session::SessionId,
        session::SessionStatus,
        session::AgentState,
        workspace::WorkspaceDef,
        workspace::StartupWorkspace,
        workspace::SetWorkspacesRequest,
        workspace::RenameWorkspaceRequest,
        workspace::DeleteWorkspaceRequest,
        workspace::SetProjectWorkspace,
        ws::ClientControl,
        ws::ServerControl,
        ws::AttachKind,
        ws::DetachReason,
    );

    fs::write(dir.join("constants.ts"), constants_ts()).expect("write constants.ts");
    fs::write(dir.join("index.ts"), index_ts(dir)).expect("write index.ts");
}

/// A JSON string literal is a valid TypeScript string literal, so serde_json
/// does the escaping.
fn ts_string(s: &str) -> String {
    serde_json::to_string(s).expect("a &str always serializes")
}

/// The wire constants a client matches on, as TypeScript.
fn constants_ts() -> String {
    let sentinel =
        serde_json::to_string(&session::COMMANDER_SENTINEL_ID).expect("a SessionId serializes");
    format!(
        "{GENERATED_HEADER}import type {{ SessionId }} from \"./SessionId\";\n\
         \n\
         /** `ServerControl.error` message for a rejected auth token (`ws::WS_ERR_AUTH`). */\n\
         export const WS_ERR_AUTH = {auth};\n\
         \n\
         /** `ServerControl.error` message for an attach to an unknown session (`ws::WS_ERR_NO_SESSION`). */\n\
         export const WS_ERR_NO_SESSION = {no_session};\n\
         \n\
         /**\n \
         * The commander's reserved id in `AgentStatesSnapshot.states`\n \
         * (`session::COMMANDER_SENTINEL_ID`). It maps to no session: skip it when\n \
         * rendering per-session rows.\n \
         */\n\
         export const COMMANDER_SENTINEL_ID: SessionId = {sentinel};\n",
        auth = ts_string(ws::WS_ERR_AUTH),
        no_session = ts_string(ws::WS_ERR_NO_SESSION),
    )
}

/// A barrel re-exporting every generated module, so the page imports from one
/// place. Built from the directory listing so it can't miss a type.
fn index_ts(dir: &Path) -> String {
    let mut modules: Vec<String> = fs::read_dir(dir)
        .expect("read export dir")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter_map(|name| name.strip_suffix(".ts").map(str::to_string))
        .filter(|stem| stem != "index")
        .collect();
    modules.sort();
    let mut out = String::from(GENERATED_HEADER);
    for m in modules {
        out.push_str(&format!("export * from \"./{m}\";\n"));
    }
    out
}

/// Every file under `dir` (non-recursive — ts-rs writes flat here), by name.
fn read_tree(dir: &Path) -> BTreeMap<String, String> {
    let Ok(entries) = fs::read_dir(dir) else {
        return BTreeMap::new();
    };
    entries
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.is_file())
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            let body = fs::read_to_string(&p).expect("read generated file");
            (name, body)
        })
        .collect()
}

#[test]
fn bindings_are_up_to_date() {
    let committed = committed_dir();
    if std::env::var_os(REGENERATE_ENV).is_some() {
        if committed.exists() {
            fs::remove_dir_all(&committed).expect("clear web/src/generated");
        }
        fs::create_dir_all(&committed).expect("create web/src/generated");
        export_into(&committed);
        return;
    }

    let fresh_dir = tempfile::TempDir::new().expect("temp dir");
    export_into(fresh_dir.path());
    let fresh = read_tree(fresh_dir.path());
    let on_disk = read_tree(&committed);

    let mut problems = Vec::new();
    for (name, body) in &fresh {
        match on_disk.get(name) {
            None => problems.push(format!("missing: {name}")),
            Some(old) if old != body => problems.push(format!("stale:   {name}")),
            Some(_) => {}
        }
    }
    for name in on_disk.keys().filter(|n| !fresh.contains_key(*n)) {
        problems.push(format!("extra:   {name}"));
    }
    assert!(
        problems.is_empty(),
        "web/src/generated/ is out of date with the protocol crate:\n  {}\n\n\
         Regenerate it with:\n  \
         {REGENERATE_ENV}=1 cargo test -p claude-commander-protocol --features ts ts_export\n\
         and commit the result.",
        problems.join("\n  ")
    );
}
