// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'review.dart';

// These functions are ignored because they are not marked as `pub`: `absent`, `build`, `cell`, `content_gutter`, `content_spans`, `emit_row`, `from_wire`, `into_owned`, `intraline_options`, `new`, `parse_all`, `parsed_review`, `strip_gutter`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TextSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `has_content`, `line_count`, `line`

/// Lay one file of a review diff out into rows of styled runs.
///
/// `raw` is [`crate::api::review::ReviewSnapshotDto::raw`]; when it is `None`
/// (a server predating that field) the layout is built from `fallback` instead,
/// which is lossier — no `\ No newline at EOF`, no CRLF flag, no rename
/// similarity — but identical for everything that is drawn.
///
/// `file_text` is the working-tree text of the file's new side, as fetched via
/// [`crate::api::review::fetch_blob`]. Without it, gaps stay collapsed and no
/// expand controls are offered; [`DiffLayoutDto::has_hidden_context`] says
/// whether fetching it would buy anything.
Future<DiffLayoutDto> diffRows({
  String? raw,
  required ReviewFileDto fallback,
  required DiffLayoutMode mode,
  String? fileText,
  required List<DiffExpansion> expansions,
  required int tabWidth,
}) => RustLib.instance.api.crateApiDiffDiffRows(
  raw: raw,
  fallback: fallback,
  mode: mode,
  fileText: fileText,
  expansions: expansions,
  tabWidth: tabWidth,
);

/// One side's contents of a row.
class DiffCellDto {
  /// `false` for the blank half of an unbalanced side-by-side pair, and for
  /// [`DiffRowDto::right`] in inline mode.
  final bool present;
  final ReviewLineOrigin? origin;
  final int? oldLineno;
  final int? newLineno;

  /// This line's index among the file's selectable lines — the stable key for
  /// cursor, selection and comment anchoring. `None` for revealed context,
  /// which is not part of the diff.
  final int? sel;
  final List<DiffSpanDto> spans;

  /// The line's text *before* tab expansion, for a comment snippet. Taken
  /// from the model rather than the spans, because a snippet the server
  /// re-anchors against has to match the file byte for byte.
  final String text;

  const DiffCellDto({
    required this.present,
    this.origin,
    this.oldLineno,
    this.newLineno,
    this.sel,
    required this.spans,
    required this.text,
  });

  @override
  int get hashCode =>
      present.hashCode ^
      origin.hashCode ^
      oldLineno.hashCode ^
      newLineno.hashCode ^
      sel.hashCode ^
      spans.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffCellDto &&
          runtimeType == other.runtimeType &&
          present == other.present &&
          origin == other.origin &&
          oldLineno == other.oldLineno &&
          newLineno == other.newLineno &&
          sel == other.sel &&
          spans == other.spans &&
          text == other.text;
}

/// A direction a gap was asked to reveal in.
enum DiffExpandAction {
  /// A step more just below the hunk above the gap.
  down,

  /// A step more just above the hunk below the gap.
  up,

  /// The whole gap at once.
  all,
}

/// One expansion the user has already asked for, replayed onto a fresh layout.
///
/// Dart appends to a list and passes the whole list back; that keeps the bridge
/// stateless without making expansion state the host's problem to *model* —
/// only to remember.
class DiffExpansion {
  /// Index of the gap, as reported by [`DiffRowDto::gap`].
  final int gap;
  final DiffExpandAction action;

  const DiffExpansion({required this.gap, required this.action});

  @override
  int get hashCode => gap.hashCode ^ action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffExpansion &&
          runtimeType == other.runtimeType &&
          gap == other.gap &&
          action == other.action;
}

/// A file laid out into rows, plus what the host needs to drive it.
class DiffLayoutDto {
  final List<DiffRowDto> rows;

  /// How many selectable lines the file has, so a host can clamp a cursor
  /// without walking the rows.
  final int selectable;

  /// The diff elides unchanged regions, so fetching the file's text would buy
  /// working expand controls. Independent of whether text was *supplied*:
  /// this is the signal to go and fetch it.
  final bool hasHiddenContext;

  const DiffLayoutDto({
    required this.rows,
    required this.selectable,
    required this.hasHiddenContext,
  });

  @override
  int get hashCode =>
      rows.hashCode ^ selectable.hashCode ^ hasHiddenContext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffLayoutDto &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          selectable == other.selectable &&
          hasHiddenContext == other.hasHiddenContext;
}

/// How to lay a file out.
enum DiffLayoutMode {
  /// One column: deletions and additions interleaved.
  inline,

  /// Two columns: old on the left, new on the right.
  sideBySide,
}

/// What a run of text *is*, semantically — the flattened form of
/// [`diffgrid::style::Role`].
///
/// `Gutter(_)` and `Padding` never reach Dart (see [`content_gutter`]), and
/// `Role` is `#[non_exhaustive]`, so anything new lands on [`Self::Other`] and
/// renders as plain text rather than failing the build.
enum DiffRole {
  context,
  addition,
  deletion,
  hunkHeader,
  expandedContext,
  other,
}

/// One laid-out row.
class DiffRowDto {
  final DiffRowKind kind;

  /// `true` for rows that span both halves side by side (hunk headers, expand
  /// controls). Only [`Self::left`] is populated for those.
  final bool fullWidth;

  /// Inline mode: the single reading of the row. Side by side: the old half.
  final DiffCellDto left;

  /// Side by side: the new half. Absent in inline mode.
  final DiffCellDto right;

  /// The gap this row belongs to, for both control and revealed-context rows.
  final int? gap;

  /// Lines still hidden by the gap ([`DiffRowKind::ExpandControl`] only).
  final int hidden;

  /// Whether the control can still reveal upward / downward. "Reveal all" is
  /// always available while `hidden > 0`.
  final bool canExpandUp;
  final bool canExpandDown;

  const DiffRowDto({
    required this.kind,
    required this.fullWidth,
    required this.left,
    required this.right,
    this.gap,
    required this.hidden,
    required this.canExpandUp,
    required this.canExpandDown,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      fullWidth.hashCode ^
      left.hashCode ^
      right.hashCode ^
      gap.hashCode ^
      hidden.hashCode ^
      canExpandUp.hashCode ^
      canExpandDown.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffRowDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          fullWidth == other.fullWidth &&
          left == other.left &&
          right == other.right &&
          gap == other.gap &&
          hidden == other.hidden &&
          canExpandUp == other.canExpandUp &&
          canExpandDown == other.canExpandDown;
}

/// What a row is.
enum DiffRowKind {
  /// An `@@ … @@` header introducing a hunk.
  hunkHeader,

  /// A diff line — the only commentable kind.
  line,

  /// A context line revealed out of a gap. Display-only: not part of the
  /// diff, so it carries no [`DiffCellDto::sel`] and cannot be commented on.
  expandedContext,

  /// A "reveal more" control for a gap. Carries no spans: Flutter draws
  /// buttons from [`DiffRowDto::hidden`] and the `can_expand_*` flags rather
  /// than centring a row of glyphs the way a terminal must.
  expandControl,

  /// The blank half of a side-by-side pair.
  alignmentGap,
}

/// A run of text with a uniform style. Concatenating a cell's spans reproduces
/// its rendered text exactly (tabs already expanded).
class DiffSpanDto {
  final String text;
  final DiffRole role;

  /// The intra-line word diff marked this run as changed. Flutter composites
  /// an emphasis tint *over* the line tint for these.
  final bool emphasis;

  const DiffSpanDto({
    required this.text,
    required this.role,
    required this.emphasis,
  });

  @override
  int get hashCode => text.hashCode ^ role.hashCode ^ emphasis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffSpanDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          role == other.role &&
          emphasis == other.emphasis;
}
