// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `narrow`

/// Score `needle` against `haystack`, Skim-style. `None` when `needle` is not a
/// subsequence of `haystack`; higher is a better match. An empty needle scores
/// `Some(0)` so a caller can filter without special-casing the empty query.
int? fuzzyScore({required String haystack, required String needle}) => RustLib
    .instance
    .api
    .crateApiQueryFuzzyScore(haystack: haystack, needle: needle);

/// Best score across a session's title, branch and program — the ranking rule
/// the TUI's palette applies. The project name is deliberately not matched.
int? sessionScore({
  required String title,
  required String branch,
  required String program,
  required String query,
}) => RustLib.instance.api.crateApiQuerySessionScore(
  title: title,
  branch: branch,
  program: program,
  query: query,
);
