// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_on`, `call`, `connection_watch`, `generation_watch`, `lock_servers`, `map_client_err`, `parse_project_id`, `parse_session_id`, `runtime`, `servers`, `with_client`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServerEntry`

/// Connect to a server: build + validate a [`RemoteClient`], spawn its poller,
/// and register both under a freshly generated opaque handle (returned). An
/// empty `token` means "auth disabled" (loopback dev) — no bearer is sent.
///
/// The URL is validated here (bad scheme/host fails now); *reachability*
/// surfaces later through the connection feed, not from this call.
Future<String> connectServer({required String baseUrl, String? token}) =>
    RustLib.instance.api.crateApiRegistryConnectServer(
      baseUrl: baseUrl,
      token: token,
    );

/// Disconnect a server: tear down any in-flight terminal attaches it owns (an
/// attach holds its own client clone, so it outlives the registry entry
/// otherwise), then drop its registry entry, which drops the [`Poller`] and
/// aborts its poll task. A no-op for an unknown handle.
Future<void> disconnectServer({required String handle}) =>
    RustLib.instance.api.crateApiRegistryDisconnectServer(handle: handle);
