// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_diff_side`, `parse_side`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReviewDiffDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Open the review snapshot (parsed diff + re-anchored comments + reviewed
/// marks) for a session, converted to DTOs.
Future<ReviewSnapshotDto> openReview({
  required String handle,
  required String sessionId,
}) => RustLib.instance.api.crateApiReviewOpenReview(
  handle: handle,
  sessionId: sessionId,
);

/// A fresh snapshot, or `None` when the diff is unchanged. `prev_hash` is the
/// `content_hash` string from a prior snapshot, parsed back to a `u64`.
Future<ReviewSnapshotDto?> refreshReview({
  required String handle,
  required String sessionId,
  required String prevHash,
}) => RustLib.instance.api.crateApiReviewRefreshReview(
  handle: handle,
  sessionId: sessionId,
  prevHash: prevHash,
);

/// The session's comments (re-anchored), as DTOs.
Future<List<CommentDto>> listComments({
  required String handle,
  required String sessionId,
}) => RustLib.instance.api.crateApiReviewListComments(
  handle: handle,
  sessionId: sessionId,
);

/// Stage a new comment, returning its id. `side` is `"old"` or `"new"`.
Future<String> createComment({
  required String handle,
  required String sessionId,
  required String file,
  required String side,
  required int lineStart,
  required int lineEnd,
  required String snippet,
  required String comment,
}) => RustLib.instance.api.crateApiReviewCreateComment(
  handle: handle,
  sessionId: sessionId,
  file: file,
  side: side,
  lineStart: lineStart,
  lineEnd: lineEnd,
  snippet: snippet,
  comment: comment,
);

/// Delete a staged comment by id.
Future<void> deleteComment({
  required String handle,
  required String sessionId,
  required String commentId,
}) => RustLib.instance.api.crateApiReviewDeleteComment(
  handle: handle,
  sessionId: sessionId,
  commentId: commentId,
);

/// Apply a session's staged comments, returning the flattened [`ApplyResult`].
Future<ApplyResult> applyComments({
  required String handle,
  required String sessionId,
}) => RustLib.instance.api.crateApiReviewApplyComments(
  handle: handle,
  sessionId: sessionId,
);

/// Raw file bytes for one side of a (binary) diff. `side` is `"old"`/`"new"`;
/// `path` is the file's display path. Used to render binary images.
Future<Uint8List> fetchBlob({
  required String handle,
  required String sessionId,
  required String side,
  required String path,
}) => RustLib.instance.api.crateApiReviewFetchBlob(
  handle: handle,
  sessionId: sessionId,
  side: side,
  path: path,
);

/// Toggle a file's reviewed mark, returning the new state. Only the display path
/// crosses the wire — the server resolves the file in the *current* review diff.
Future<bool> toggleFileReviewed({
  required String handle,
  required String sessionId,
  required String displayPath,
}) => RustLib.instance.api.crateApiReviewToggleFileReviewed(
  handle: handle,
  sessionId: sessionId,
  displayPath: displayPath,
);

/// Outcome of applying a session's staged comments — a tagged struct (not a
/// data enum), following the [`crate::api::terminal::TerminalEvent`] rule.
class ApplyResult {
  final ApplyResultKind kind;

  /// Ids of drifted comments (populated only for [`ApplyResultKind::Blocked`]).
  final List<String> driftedIds;

  /// Path the brief was composed to (`Applied`/`Deferred`); `None` otherwise.
  final String? path;

  /// Number of comments composed (`Applied`/`Deferred`); `0` otherwise.
  final int count;

  const ApplyResult({
    required this.kind,
    required this.driftedIds,
    this.path,
    required this.count,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ driftedIds.hashCode ^ path.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyResult &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          driftedIds == other.driftedIds &&
          path == other.path &&
          count == other.count;
}

/// Which kind of [`ApplyResult`] this is (unit enum, so frb renders a plain Dart
/// enum rather than a freezed class). Flattens the data-carrying
/// [`ApplyOutcome`].
enum ApplyResultKind {
  /// No staged comments to apply.
  nothing,

  /// One or more comments are drifted; nothing was sent.
  blocked,

  /// Comments were composed and the prompt injected.
  applied,

  /// The brief was written but couldn't be delivered; the user can re-apply.
  deferred_,
}

/// A single review comment. `line_range: (usize, usize)` is split into
/// `line_start`/`line_end`; the id is exposed as a `String`.
class CommentDto {
  final String id;
  final String file;
  final ReviewCommentSide side;
  final int lineStart;
  final int lineEnd;
  final String snippet;
  final String comment;
  final ReviewCommentStatus status;
  final DateTime createdAt;

  const CommentDto({
    required this.id,
    required this.file,
    required this.side,
    required this.lineStart,
    required this.lineEnd,
    required this.snippet,
    required this.comment,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      file.hashCode ^
      side.hashCode ^
      lineStart.hashCode ^
      lineEnd.hashCode ^
      snippet.hashCode ^
      comment.hashCode ^
      status.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          file == other.file &&
          side == other.side &&
          lineStart == other.lineStart &&
          lineEnd == other.lineEnd &&
          snippet == other.snippet &&
          comment == other.comment &&
          status == other.status &&
          createdAt == other.createdAt;
}

/// Which side of the diff a comment range refers to (unit-enum mirror of
/// [`CommentSide`]).
enum ReviewCommentSide { old, new_ }

/// Lifecycle status of a comment (unit-enum mirror of [`CommentStatus`]).
enum ReviewCommentStatus { staged, drifted, applied }

/// All changes to a single file. `BinaryKind`/`BinaryInfo` are flattened onto
/// `is_binary` + `binary_mime`; the blob bytes are fetched lazily via
/// [`fetch_blob`].
class ReviewFileDto {
  /// Path to show in the file list (new path, or old path for deletions).
  final String displayPath;
  final String oldPath;
  final String newPath;
  final ReviewFileStatus status;
  final int added;
  final int removed;
  final List<ReviewHunkDto> hunks;
  final bool isBinary;

  /// `Some(mime)` when the binary is a renderable image; `None` otherwise.
  final String? binaryMime;

  const ReviewFileDto({
    required this.displayPath,
    required this.oldPath,
    required this.newPath,
    required this.status,
    required this.added,
    required this.removed,
    required this.hunks,
    required this.isBinary,
    this.binaryMime,
  });

  @override
  int get hashCode =>
      displayPath.hashCode ^
      oldPath.hashCode ^
      newPath.hashCode ^
      status.hashCode ^
      added.hashCode ^
      removed.hashCode ^
      hunks.hashCode ^
      isBinary.hashCode ^
      binaryMime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewFileDto &&
          runtimeType == other.runtimeType &&
          displayPath == other.displayPath &&
          oldPath == other.oldPath &&
          newPath == other.newPath &&
          status == other.status &&
          added == other.added &&
          removed == other.removed &&
          hunks == other.hunks &&
          isBinary == other.isBinary &&
          binaryMime == other.binaryMime;
}

/// How a file changed (unit-enum mirror of [`FileStatus`]).
enum ReviewFileStatus { added, deleted, modified, renamed }

/// A contiguous block of changes (one `@@ ... @@` section).
class ReviewHunkDto {
  final int oldStart;
  final int oldLines;
  final int newStart;
  final int newLines;

  /// Section heading following the closing `@@`, if any.
  final String header;
  final List<ReviewLineDto> lines;

  const ReviewHunkDto({
    required this.oldStart,
    required this.oldLines,
    required this.newStart,
    required this.newLines,
    required this.header,
    required this.lines,
  });

  @override
  int get hashCode =>
      oldStart.hashCode ^
      oldLines.hashCode ^
      newStart.hashCode ^
      newLines.hashCode ^
      header.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewHunkDto &&
          runtimeType == other.runtimeType &&
          oldStart == other.oldStart &&
          oldLines == other.oldLines &&
          newStart == other.newStart &&
          newLines == other.newLines &&
          header == other.header &&
          lines == other.lines;
}

/// A single diff line with resolved old/new line numbers.
class ReviewLineDto {
  final ReviewLineOrigin origin;

  /// `None` for additions.
  final int? oldLineno;

  /// `None` for deletions.
  final int? newLineno;

  /// Line content without the leading `+`/`-`/space marker.
  final String content;

  const ReviewLineDto({
    required this.origin,
    this.oldLineno,
    this.newLineno,
    required this.content,
  });

  @override
  int get hashCode =>
      origin.hashCode ^
      oldLineno.hashCode ^
      newLineno.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewLineDto &&
          runtimeType == other.runtimeType &&
          origin == other.origin &&
          oldLineno == other.oldLineno &&
          newLineno == other.newLineno &&
          content == other.content;
}

/// Origin of a single diff line (unit-enum mirror of [`LineOrigin`]).
enum ReviewLineOrigin { context, addition, deletion }

/// Result of opening the review view. `content_hash` is a `u64` server-side;
/// it's exposed as a `String` because a Dart `int` can't hold all `u64` values
/// (and the value is only ever echoed back to `refresh_review`).
class ReviewSnapshotDto {
  final String base;
  final String contentHash;
  final List<ReviewFileDto> files;
  final List<CommentDto> comments;

  /// Display paths of files still marked reviewed.
  final List<String> reviewed;

  /// The raw unified diff the snapshot was parsed from, to be handed straight
  /// back to [`diff_rows`] for layout. `None` against a server predating the
  /// field, in which case `diff_rows` falls back to `files`.
  final String? raw;

  const ReviewSnapshotDto({
    required this.base,
    required this.contentHash,
    required this.files,
    required this.comments,
    required this.reviewed,
    this.raw,
  });

  @override
  int get hashCode =>
      base.hashCode ^
      contentHash.hashCode ^
      files.hashCode ^
      comments.hashCode ^
      reviewed.hashCode ^
      raw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewSnapshotDto &&
          runtimeType == other.runtimeType &&
          base == other.base &&
          contentHash == other.contentHash &&
          files == other.files &&
          comments == other.comments &&
          reviewed == other.reviewed &&
          raw == other.raw;
}
