// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `probe_client`

/// Liveness probe: `GET {base_url}/health` (no auth). Returns true on a 2xx.
/// Called by the connect screen before any server handle exists.
Future<bool> health({required String baseUrl}) =>
    RustLib.instance.api.crateApiSimpleHealth(baseUrl: baseUrl);

/// Authenticated tmux probe: `GET {base_url}/api/health/tmux`. 200 → true, 503 →
/// false; a 401/403 surfaces as an auth error. Doubles as an auth check for the
/// connect screen.
Future<bool> healthTmux({required String baseUrl, required String token}) =>
    RustLib.instance.api.crateApiSimpleHealthTmux(
      baseUrl: baseUrl,
      token: token,
    );

/// The whole workspace snapshot (projects, sessions, cascade/pending/pull state,
/// operations ledger, server health) in one shot.
Future<WorkspaceSnapshotDto> workspaceSnapshot({required String handle}) =>
    RustLib.instance.api.crateApiSimpleWorkspaceSnapshot(handle: handle);

/// Bulk agent-state snapshot (the commander sentinel entry is stripped by the
/// DTO). `fresh` forces a re-detection rather than a cached read.
Future<AgentStatesSnapshotDto> agentStates({
  required String handle,
  required bool fresh,
}) => RustLib.instance.api.crateApiSimpleAgentStates(
  handle: handle,
  fresh: fresh,
);

/// Compatibility shim for the current session-list page: the sessions from the
/// workspace snapshot, optionally filtering out stopped ones client-side. The
/// app moves to snapshot-driven state in Phase 3; until then this keeps the list
/// page + its tests unchanged.
Future<List<SessionInfo>> listSessions({
  required String handle,
  required bool includeStopped,
}) => RustLib.instance.api.crateApiSimpleListSessions(
  handle: handle,
  includeStopped: includeStopped,
);

/// A session's live detail (agent state, diff summary, pane snapshot). `query`
/// is matched loosely server-side (full id, branch, or title prefix); a 404
/// returns `None` so a deleted session reads as "gone".
Future<SessionDetail?> getSessionDetail({
  required String handle,
  required String query,
  int? lines,
}) => RustLib.instance.api.crateApiSimpleGetSessionDetail(
  handle: handle,
  query: query,
  lines: lines,
);

/// Preview payload for a session (agent pane + diff text/stat + shell pane).
Future<PreviewDataDto> sessionPreview({
  required String handle,
  required String id,
  int? lines,
}) => RustLib.instance.api.crateApiSimpleSessionPreview(
  handle: handle,
  id: id,
  lines: lines,
);

/// Preview payload for a project (diff text/stat; no agent pane).
Future<PreviewDataDto> projectPreview({
  required String handle,
  required String id,
}) => RustLib.instance.api.crateApiSimpleProjectPreview(handle: handle, id: id);

/// The raw unified diff (base → working tree) for a session's branch.
Future<String> branchDiff({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleBranchDiff(handle: handle, id: id);

/// Branches for a project's base-branch picker. `fetch` runs a `git fetch` first.
Future<List<BranchInfo>> listBranches({
  required String handle,
  required String projectId,
  required bool fetch,
}) => RustLib.instance.api.crateApiSimpleListBranches(
  handle: handle,
  projectId: projectId,
  fetch: fetch,
);

/// Options for the new-session dialog (default program, program list, sections).
Future<CreateOptions> createOptions({required String handle}) =>
    RustLib.instance.api.crateApiSimpleCreateOptions(handle: handle);

/// Replace the server's configured program list wholesale.
Future<void> setPrograms({
  required String handle,
  required List<ProgramInfo> programs,
}) => RustLib.instance.api.crateApiSimpleSetPrograms(
  handle: handle,
  programs: programs,
);

/// Sessions with at least one not-yet-applied review comment.
Future<List<SessionId>> pendingCommentSessions({required String handle}) =>
    RustLib.instance.api.crateApiSimplePendingCommentSessions(handle: handle);

/// Create a session; returns the new session's full-id string. `project_path` is
/// a path on the *server's* filesystem.
Future<String> createSession({
  required String handle,
  required String projectPath,
  required String title,
  String? program,
  String? initialPrompt,
  String? effort,
  String? mode,
  String? baseBranch,
}) => RustLib.instance.api.crateApiSimpleCreateSession(
  handle: handle,
  projectPath: projectPath,
  title: title,
  program: program,
  initialPrompt: initialPrompt,
  effort: effort,
  mode: mode,
  baseBranch: baseBranch,
);

/// Stop a running session (its worktree is kept).
Future<void> killSession({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleKillSession(handle: handle, id: id);

/// Restart a session's program.
Future<void> restartSession({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleRestartSession(handle: handle, id: id);

/// Delete a session, its branch, and its worktree.
Future<void> deleteSession({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleDeleteSession(handle: handle, id: id);

/// Rename a session's title.
Future<void> renameSession({
  required String handle,
  required String id,
  required String title,
}) => RustLib.instance.api.crateApiSimpleRenameSession(
  handle: handle,
  id: id,
  title: title,
);

/// Move a session to a section; `section: None` clears the manual override.
Future<void> setSection({
  required String handle,
  required String id,
  String? section,
}) => RustLib.instance.api.crateApiSimpleSetSection(
  handle: handle,
  id: id,
  section: section,
);

/// Mark a session read (clears its unread indicator).
Future<void> markRead({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleMarkRead(handle: handle, id: id);

/// Mark a batch of sessions unread (unknown ids are skipped server-side).
Future<void> markUnread({required String handle, required List<String> ids}) =>
    RustLib.instance.api.crateApiSimpleMarkUnread(handle: handle, ids: ids);

/// Toggle a session's keep-alive (idle-hibernation exemption); returns the new
/// state.
Future<bool> toggleKeepAlive({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleToggleKeepAlive(handle: handle, id: id);

/// Upload an image to a session's agent pane (`POST /paste-image`).
///
/// The server writes the bytes to a temp file and types the path into the agent
/// pane without pressing Enter, so the user can add prompt text around it — the
/// form the Claude CLI accepts. The path shows up in the terminal view through
/// the normal attach output stream, so a caller needs no success feedback.
///
/// `bytes` are whatever the platform picker or clipboard produced;
/// [`RemoteClient::paste_image`] sniffs the content and refuses anything that
/// isn't an allow-listed image (or is over
/// [`claude_commander_protocol::paste::MAX_IMAGE_BYTES`]) *before* uploading, so
/// a doomed transfer never leaves the device.
Future<void> pasteImage({
  required String handle,
  required String id,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiSimplePasteImage(
  handle: handle,
  id: id,
  bytes: bytes,
);

/// The pasted-image size cap in bytes, so the UI can reject an oversized pick
/// from its file length — without reading a 50 MB phone photo into memory just
/// to discard it — using the shared wire contract rather than a hardcoded Dart
/// mirror that could drift.
///
/// `u32` (not `usize`/`u64`) so this lands in Dart as a plain `int` rather than a
/// `BigInt`; the cap is single-digit MiB and will never approach 4 GiB. The
/// const assert below makes that an enforced precondition rather than a comment,
/// so raising the cap past `u32::MAX` fails the build instead of silently
/// truncating.
Future<int> imageMaxBytes() =>
    RustLib.instance.api.crateApiSimpleImageMaxBytes();

/// How long a silent client can be away before the server is *guaranteed* to
/// have torn its terminal attach down, in milliseconds.
///
/// The mobile UI needs this on resume: a frozen background process can't answer
/// the server's heartbeat pings, so an absence longer than this means the attach
/// is certainly gone and must be re-opened, while a shorter one proves nothing —
/// leaving a live socket alone there is what keeps a scrolled tmux copy-mode view
/// in place. Sourced from the shared wire contract rather than a hardcoded Dart
/// threshold, which would drift silently the moment the heartbeat is retuned.
///
/// `u32` milliseconds (not a `Duration`) so this crosses the bridge as a plain
/// Dart `int`; the const assert makes the range a build-time precondition rather
/// than a comment.
Future<int> attachDeadAfterMillis() =>
    RustLib.instance.api.crateApiSimpleAttachDeadAfterMillis();

/// Register a project (git repo) by server-side path; returns the new project's
/// full-id string.
Future<String> addProject({required String handle, required String path}) =>
    RustLib.instance.api.crateApiSimpleAddProject(handle: handle, path: path);

/// Register a project by server-side path, or return the id of the project
/// already registered for it; returns a full-id string either way.
///
/// The idempotent counterpart to [`add_project`], and what a "register this
/// existing checkout" offer must call: the path it was handed is frequently
/// already a project, and `add_project` would register a second entry for the
/// same repository. The dedupe (including how a path is resolved to a repository)
/// is the server's — no client restates the rule.
Future<String> ensureProject({required String handle, required String path}) =>
    RustLib.instance.api.crateApiSimpleEnsureProject(
      handle: handle,
      path: path,
    );

/// Remove a project (its sessions must already be gone).
Future<void> removeProject({required String handle, required String id}) =>
    RustLib.instance.api.crateApiSimpleRemoveProject(handle: handle, id: id);

/// Scan a server-side directory for git repos, registering any new ones.
Future<ScanResultDto> scanDirectory({
  required String handle,
  required String path,
}) => RustLib.instance.api.crateApiSimpleScanDirectory(
  handle: handle,
  path: path,
);

/// Every repo the server-side `gh` user can clone, for the repo picker.
///
/// The list is the *server's* to produce: `gh` runs where the checkout will land,
/// so a phone with no `gh` and no GitHub credentials still gets a picker. A server
/// without `gh` answers 503, which arrives here as an error a UI can word as
/// "install gh on the server" rather than as a generic failure.
Future<List<GithubRepo>> githubRepos({required String handle}) =>
    RustLib.instance.api.crateApiSimpleGithubRepos(handle: handle);

/// Provider-neutral repository listing, including the selected host identity
/// even when no repositories are returned.
Future<RepositoryListing> repositories({required String handle}) =>
    RustLib.instance.api.crateApiSimpleRepositories(handle: handle);

/// Start a clone, returning the created job (the route answers 202 with the whole
/// job, so the id, the destination and the first status arrive together).
///
/// **The returned status is not a terminal status.** Every outcome — success,
/// failure, and an already-occupied destination — is reported through
/// [`clone_job`], so this reads `Running` essentially always. Poll from here; the
/// cadence is the caller's (nothing in this crate loops).
///
/// An unusable source or destination name is refused with a 400, which surfaces
/// as an error carrying the server's *already-redacted* reason. Nothing on this
/// path builds a message out of the request's source: a hand-pasted URL can carry
/// `user:token@` userinfo, and the rejection strings are redacted where they are
/// constructed in `claude-commander-protocol` precisely so no hop has to remember
/// to.
Future<CloneJobDto> startClone({
  required String handle,
  required CloneRequestDto request,
}) => RustLib.instance.api.crateApiSimpleStartClone(
  handle: handle,
  request: request,
);

/// One poll of a clone job.
///
/// **`None` is a normal answer, not an error.** The server prunes jobs a while
/// after they finish, so a client that keeps polling (or resumes with an id it
/// stored across a restart) must read "gone" rather than a failure it would
/// surface as a broken connection.
///
/// Takes the typed [`CloneJobId`] straight off the job [`start_clone`] returned,
/// unlike the session/project routes above which take a full-UUID `String`. Those
/// ids reach Dart as strings already (`SessionInfo.id`, `create_session`); a clone
/// job id only ever comes from a `CloneJobDto`, so a `String` parameter would add
/// a stringify-and-reparse round trip that can only introduce failures.
Future<CloneJobDto?> cloneJob({
  required String handle,
  required CloneJobId id,
}) => RustLib.instance.api.crateApiSimpleCloneJob(handle: handle, id: id);

/// Reduce a clone source to a stable `host/owner/name` identity, or `None` when it
/// has none (a local path or a `file://` URL — a local checkout has no GitHub
/// identity, so it never earns an "already added" badge).
///
/// Pure string work with no server involved, so it needs no handle. Exposed so
/// the repo picker's badge compares canonical forms through
/// [`claude_commander_protocol::github::canonical_repo_slug`] — the single
/// definition the server and the Rust client already use — rather than through a
/// second Dart implementation of the rule. Raw strings would miss most matches:
/// `gh repo clone` honours the user's configured `git_protocol`, so a repo cloned
/// by `gh` typically has an `ssh://` origin while the API reports `https://`.
///
/// Safe to feed a credentialed URL: the host is taken after the userinfo
/// delimiter (`github.rs`'s `host_of` splits on the last `@`), so a
/// `user:token@` component never reaches the returned slug.
Future<String?> canonicalRepoSlug({required String url}) =>
    RustLib.instance.api.crateApiSimpleCanonicalRepoSlug(url: url);

/// Cascade-merge a session down its stack; returns the recorded operation.
Future<OperationStatusDto> cascadeMerge({
  required String handle,
  required String id,
}) => RustLib.instance.api.crateApiSimpleCascadeMerge(handle: handle, id: id);

/// Push a session's whole stack; returns the recorded operation.
Future<OperationStatusDto> pushStack({
  required String handle,
  required String id,
}) => RustLib.instance.api.crateApiSimplePushStack(handle: handle, id: id);

/// Resume a paused cascade (after the conflict was resolved); returns the op.
Future<OperationStatusDto> cascadeResume({required String handle}) =>
    RustLib.instance.api.crateApiSimpleCascadeResume(handle: handle);

/// Abandon a paused cascade.
Future<void> cascadeAbandon({required String handle}) =>
    RustLib.instance.api.crateApiSimpleCascadeAbandon(handle: handle);

/// Ask the server to re-check PR metadata (runs its PR-status loop).
Future<void> requestPrRefresh({required String handle}) =>
    RustLib.instance.api.crateApiSimpleRequestPrRefresh(handle: handle);

/// Result of scanning a directory for git repos to register.
class ScanResultDto {
  final int added;
  final int skipped;

  const ScanResultDto({required this.added, required this.skipped});

  @override
  int get hashCode => added.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResultDto &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          skipped == other.skipped;
}
