// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detach_all_for_handle`, `detached`, `error`, `lock_registry`, `output`, `pump`, `ready`, `registry`, `remove_if_current`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachEntry`, `Outbound`

/// Open a live terminal attach against the server behind `handle`. `attach_id` is
/// a caller-supplied, per-attach id (a fresh UUID) that keys this attach's
/// control channel; `session_id` is a full-id string; `kind` picks the agent or
/// shell pane. Later `terminal_send_input`/`terminal_resize`/`terminal_detach`
/// calls with the same `attach_id` route here. Events stream over `sink` until it
/// ends.
Stream<TerminalEvent> attachTerminal({
  required String handle,
  required String attachId,
  required String sessionId,
  required AttachKind kind,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalAttachTerminal(
  handle: handle,
  attachId: attachId,
  sessionId: sessionId,
  kind: kind,
  cols: cols,
  rows: rows,
);

/// Send keystrokes / raw input bytes to the attach with `attach_id`. No-op if the
/// id isn't attached (e.g. already detached).
Future<void> terminalSendInput({
  required String attachId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalTerminalSendInput(
  attachId: attachId,
  bytes: bytes,
);

/// Tell the remote PTY the viewport changed.
Future<void> terminalResize({
  required String attachId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalTerminalResize(
  attachId: attachId,
  cols: cols,
  rows: rows,
);

/// Detach (leaves the tmux session running server-side).
Future<void> terminalDetach({required String attachId}) =>
    RustLib.instance.api.crateApiTerminalTerminalDetach(attachId: attachId);

/// Stream the server's change-feed generation counter: the poller bumps it
/// whenever observable state moves (or on reconnect), and Dart re-fetches the
/// workspace snapshot on each new value. The stream ends when the server is
/// disconnected (the poller's watch closes).
Stream<BigInt> changeFeed({required String handle}) =>
    RustLib.instance.api.crateApiTerminalChangeFeed(handle: handle);

/// Stream the server's [`ConnectionState`](claude_commander_protocol::connection::ConnectionState)
/// as a [`ConnectionStateDto`] for the health header. Ends when the server is
/// disconnected.
Stream<ConnectionStateDto> connectionFeed({required String handle}) =>
    RustLib.instance.api.crateApiTerminalConnectionFeed(handle: handle);

/// An event streamed from an attached terminal to Dart.
///
/// Modelled as a tagged struct (not a data-carrying enum) so frb generates a
/// plain Dart class — keeping the bridge free of the freezed/build_runner step.
class TerminalEvent {
  final TerminalEventKind kind;

  /// Populated only for [`TerminalEventKind::Output`]; empty otherwise.
  final Uint8List bytes;

  /// Session label (`Ready`), detach reason (`Detached`), or error message
  /// (`Error`); empty for `Output`.
  final String text;

  const TerminalEvent({
    required this.kind,
    required this.bytes,
    required this.text,
  });

  @override
  int get hashCode => kind.hashCode ^ bytes.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          bytes == other.bytes &&
          text == other.text;
}

/// Which kind of [`TerminalEvent`] this is. A unit-only enum so frb renders a
/// plain Dart enum (no freezed).
enum TerminalEventKind {
  /// Handshake done; `text` is a session label (may be empty).
  ready,

  /// Raw PTY output bytes in `bytes` — feed straight to the terminal emulator,
  /// which handles partial UTF-8 / escape sequences.
  output,

  /// The attach ended cleanly; `text` is the reason (client detach, session
  /// ended).
  detached,

  /// A handshake or steady-state error; `text` is safe to show the user.
  error,
}
