// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirrors.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Merge every server's workspaces into the one list the app shows, in the
/// order the sources are given (the first configured server first). Main is
/// always the first entry. See `viewmodel::workspace::merge_workspace_sources`
/// for the rules.
List<MergedWorkspace> mergeWorkspaces({
  required List<WorkspaceSourceDto> sources,
}) => RustLib.instance.api.crateApiWorkspaceMergeWorkspaces(sources: sources);

/// Which workspace to show, given a server's `startup_workspace` string
/// (`"last"`, `"main"` or a name), the one this device last had active, and the
/// merged list. `None` is Main — including when the wanted workspace does not
/// exist (yet).
String? resolveStartupWorkspace({
  required String startup,
  String? last,
  required List<MergedWorkspace> workspaces,
}) => RustLib.instance.api.crateApiWorkspaceResolveStartupWorkspace(
  startup: startup,
  last: last,
  workspaces: workspaces,
);

/// Whether `name` is already taken — by a workspace or by Main's label,
/// trimmed and ignoring case, as a server compares them. `except` is the
/// workspace being renamed, which may keep (or re-case) its own name.
bool workspaceNameTaken({
  required List<MergedWorkspace> workspaces,
  required String name,
  MergedWorkspace? except,
}) => RustLib.instance.api.crateApiWorkspaceWorkspaceNameTaken(
  workspaces: workspaces,
  name: name,
  except: except,
);

/// The definition list to send one server: `wanted` (what an edit produced
/// from the merged list) narrowed to what that server accepts, given its `own`
/// definitions and the Main label it will have (`main_label`: the one being
/// sent, else its stored one). Keeps the server's own spellings and drops
/// another server's case-insensitive clash, so servers that disagree never
/// block an edit on each other.
List<WorkspaceDef> definitionsForServer({
  required List<WorkspaceDef> wanted,
  required List<WorkspaceDef> own,
  String? mainLabel,
}) => RustLib.instance.api.crateApiWorkspaceDefinitionsForServer(
  wanted: wanted,
  own: own,
  mainLabel: mainLabel,
);

/// Why `raw` cannot be a workspace name, or `None` when it can. The message is
/// the one the server would answer a 400 with.
String? workspaceNameError({required String raw}) =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceNameError(raw: raw);

/// Why `raw` cannot be Main's display label, or `None` when it can. Laxer than
/// [`workspace_name_error`]: Main may be labelled "Main".
String? workspaceLabelError({required String raw}) =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceLabelError(raw: raw);

/// One entry of the merged list. `name` is the identity (`None` = Main); `label`
/// is what to show, which only differs from `name` for Main.
class MergedWorkspace {
  final String? name;
  final String label;

  const MergedWorkspace({this.name, required this.label});

  @override
  int get hashCode => name.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergedWorkspace &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          label == other.label;
}

/// One server's contribution to the merged workspace list: its definitions, its
/// Main label override, and the tags on its projects (so a tag with no
/// definition still shows up as a workspace, and its projects stay reachable).
class WorkspaceSourceDto {
  final List<WorkspaceDef> defs;
  final WorkspaceDef? main;
  final List<String> projectTags;

  const WorkspaceSourceDto({
    required this.defs,
    this.main,
    required this.projectTags,
  });

  @override
  int get hashCode => defs.hashCode ^ main.hashCode ^ projectTags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSourceDto &&
          runtimeType == other.runtimeType &&
          defs == other.defs &&
          main == other.main &&
          projectTags == other.projectTags;
}
